# Generated by Django 5.0.4 on 2024-05-05 20:37

from __future__ import unicode_literals

import json
from pathlib import Path

from django.db import migrations


def add_counties(apps, schema_editor):
    # We can't import the County model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    County = apps.get_model("django_ke_counties", "County")
    SubCounty = apps.get_model("django_ke_counties", "SubCounty")
    Ward = apps.get_model("django_ke_counties", "Ward")

    filepath = (Path(__file__).parent).joinpath("fixtures/county_data.json")

    with open(filepath) as f:
        data = json.load(f)
        for county in data:
            saved_county, _ = County.objects.get_or_create(name=county["name"])
            for sub_county in county["sub_counties"]:
                saved_sub_county, _ = SubCounty.objects.get_or_create(
                    county=saved_county, name=sub_county["name"]
                )

                for index, ward in enumerate(sub_county["wards"]):
                    saved_ward, _ = Ward.objects.get_or_create(
                        sub_county=saved_sub_county, name=sub_county["wards"][index]
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ke_counties", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_counties),
    ]
