# The name of the action
name: Django Ke Counties Tests
# When the action is triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET_KEY: "1k22rls(k-^1r-ms2)@!wygo71ot67meie%pv3vh5gf1hk+_at"
  DEBUG: "on"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: localhost
  DB_PORT: 5432
# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: postgres
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            # Maps tcp port 5432 on service container to the host
            - 5432:5432
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.11.5
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Move into the Django project folder (.) and run pytest
      - name: Test with pytest
        working-directory: .
        run: |
            export DJANGO_SETTINGS_MODULE=mysite.settings
            pytest -vv
